name: rng
description: An enhanced random number generator
version: 0.8.0
homepage: https://github.com/OpenDICOMweb/sdk/core
author: Jim Philbin <jfphilbin@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  charcode: any

dev_dependencies:
  test: ^1.0.0
  test_tools:
    path: C:/odw/test_tools
    version: ^0.8.0

